title: Strata by HTML5 UP
description: >
  JANE DOE
  Scientist, Writer.
copyright: 
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: 
facebook_username:
twitter_username: 
linkedin_username: "carolob"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "cobri"
feed_icon: 
email:
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
